# Generated by Django 3.1.3 on 2020-12-19 20:57

import colorfield.fields
import designdef.models.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [("contenttypes", "0002_remove_content_type_name")]

    operations = [
        migrations.CreateModel(
            name="ElementType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("needs", models.TextField(blank=True, default="")),
                ("contributions", models.TextField(blank=True, default="")),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_designdef.elementtype_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={"verbose_name_plural": "element types", "ordering": ["name"]},
            managers=[
                ("tagged", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MapElementTypeStyle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_designdef.mapelementtypestyle_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "style of map element type",
                "verbose_name_plural": "styles of map element types",
                "ordering": ["theme", "map_element_type"],
            },
        ),
        migrations.CreateModel(
            name="Shape",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "map_projection",
                    models.CharField(default="EPSG:3857", max_length=50),
                ),
                ("edit_zoom", models.PositiveSmallIntegerField(default=19)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_designdef.shape_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={"abstract": False, "base_manager_name": "objects"},
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "shape_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="designdef.shape",
                    ),
                ),
                ("geom", djgeojson.fields.PointField()),
                (
                    "radius",
                    models.FloatField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("designdef.shape",),
        ),
        migrations.CreateModel(
            name="CircleStyle",
            fields=[
                (
                    "mapelementtypestyle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="designdef.mapelementtypestyle",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(default="#FFFFFF", max_length=18),
                ),
                ("weight", models.PositiveSmallIntegerField(default=2)),
                (
                    "opacity",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "dash_array",
                    models.CharField(
                        blank=True,
                        help_text="Example: 5-5",
                        max_length=50,
                        validators=[designdef.models.validators.validate_dash_array],
                    ),
                ),
                ("icon", models.ImageField(null=True, upload_to="")),
            ],
            options={"abstract": False},
            bases=("designdef.mapelementtypestyle", models.Model),
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "shape_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="designdef.shape",
                    ),
                ),
                ("geom", djgeojson.fields.LineStringField()),
            ],
            options={"abstract": False},
            bases=("designdef.shape",),
        ),
        migrations.CreateModel(
            name="LineStyle",
            fields=[
                (
                    "mapelementtypestyle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="designdef.mapelementtypestyle",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(default="#FFFFFF", max_length=18),
                ),
                ("weight", models.PositiveSmallIntegerField(default=2)),
                (
                    "opacity",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "dash_array",
                    models.CharField(
                        blank=True,
                        help_text="Example: 5-5",
                        max_length=50,
                        validators=[designdef.models.validators.validate_dash_array],
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("designdef.mapelementtypestyle", models.Model),
        ),
        migrations.CreateModel(
            name="MapElementType",
            fields=[
                (
                    "elementtype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="designdef.elementtype",
                    ),
                ),
                (
                    "shape_ctype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                        validators=[designdef.models.validators.validate_shape_ctype],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "map element types",
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("designdef.elementtype",),
            managers=[
                ("tagged", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MultiPolygon",
            fields=[
                (
                    "shape_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="designdef.shape",
                    ),
                ),
                ("geom", djgeojson.fields.MultiPolygonField()),
            ],
            options={"abstract": False},
            bases=("designdef.shape",),
        ),
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "shape_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="designdef.shape",
                    ),
                ),
                ("geom", djgeojson.fields.PointField()),
            ],
            options={"abstract": False},
            bases=("designdef.shape",),
        ),
        migrations.CreateModel(
            name="PointStyle",
            fields=[
                (
                    "mapelementtypestyle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="designdef.mapelementtypestyle",
                    ),
                ),
                ("icon", models.ImageField(null=True, upload_to="")),
            ],
            options={"abstract": False},
            bases=("designdef.mapelementtypestyle", models.Model),
        ),
        migrations.CreateModel(
            name="Polygon",
            fields=[
                (
                    "shape_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="designdef.shape",
                    ),
                ),
                ("geom", djgeojson.fields.PolygonField()),
            ],
            options={"abstract": False},
            bases=("designdef.shape",),
        ),
        migrations.CreateModel(
            name="PolygonStyle",
            fields=[
                (
                    "mapelementtypestyle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="designdef.mapelementtypestyle",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(default="#FFFFFF", max_length=18),
                ),
                ("weight", models.PositiveSmallIntegerField(default=2)),
                (
                    "opacity",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "dash_array",
                    models.CharField(
                        blank=True,
                        help_text="Example: 5-5",
                        max_length=50,
                        validators=[designdef.models.validators.validate_dash_array],
                    ),
                ),
                (
                    "fill_color",
                    colorfield.fields.ColorField(default="#FFFFFF", max_length=18),
                ),
                (
                    "fill_opacity",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("designdef.mapelementtypestyle", models.Model),
        ),
        migrations.AddField(
            model_name="mapelementtypestyle",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="styles",
                to="designdef.theme",
            ),
        ),
        migrations.AddField(
            model_name="mapelementtypestyle",
            name="map_element_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="styles",
                to="designdef.mapelementtype",
            ),
        ),
    ]
