# Generated by Django 3.0.3 on 2020-03-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="defaultdrawingclass", name="drawing_class"),
        migrations.RemoveField(model_name="feature", name="drawing_class"),
        migrations.RemoveField(model_name="feature", name="drawing_options"),
        migrations.RemoveField(model_name="featuretype", name="default_drawing_class"),
        migrations.AddField(
            model_name="featuretype",
            name="shape_model",
            field=models.CharField(
                choices=[
                    ("Circle", "Circle"),
                    ("Line", "Line"),
                    ("MultiPolygon", "MultiPolygon"),
                    ("Point", "Point"),
                    ("Polygon", "Polygon"),
                ],
                default="Polygon",
                max_length=70,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="DefaultCategory"),
        migrations.DeleteModel(name="DefaultDrawingClass"),
        migrations.DeleteModel(name="DrawingClass"),
    ]
