# Generated by Django 3.0.3 on 2020-03-28 16:28

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="featuretype",
            old_name="shape_model",
            new_name="shape_model_name",
        ),
        migrations.CreateModel(
            name="FeatureStyle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("style", jsonfield.fields.JSONField(blank=True, default=dict)),
                (
                    "feature_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.FeatureType",
                    ),
                ),
            ],
            options={"verbose_name_plural": "feature styles"},
        ),
        migrations.AddField(
            model_name="feature",
            name="style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.FeatureStyle",
            ),
        ),
    ]
