# Generated by Django 3.0.3 on 2020-04-02 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuretype",
            name="feature_ctype",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.ContentType",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="featuretype",
            name="shape_ctype",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.ContentType",
            ),
        ),
    ]
