# Generated by Django 3.0.3 on 2020-03-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="drawingclass",
            name="slug",
            field=models.SlugField(default="", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project", name="slug", field=models.SlugField(unique=True)
        ),
    ]
