# Generated by Django 3.0.3 on 2020-03-28 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="shape",
            name="id",
            field=models.AutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shape",
            name="feature",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.Feature"
            ),
        ),
    ]
