# Generated by Django 3.0.3 on 2020-03-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0002_auto_20200326_1548")]

    operations = [
        migrations.AlterModelOptions(
            name="defaultcategory",
            options={"verbose_name_plural": "default categories"},
        ),
        migrations.AlterModelOptions(
            name="drawingclass", options={"verbose_name_plural": "drawing classes"}
        ),
        migrations.RenameField(
            model_name="defaultcategory", old_name="feature", new_name="feature_model"
        ),
    ]
