# Generated by Django 3.0.3 on 2020-03-06 10:54

import api.models.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0002_auto_20200306_1050")]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="map_lat",
            field=api.models.fields.LatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="map_lng",
            field=api.models.fields.LngField(
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ]
            ),
        ),
    ]
