# Generated by Django 3.0.3 on 2020-04-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0002_auto_20200403_1931")]

    operations = [
        migrations.CreateModel(
            name="Borders",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.Project"
                    ),
                ),
            ],
        )
    ]
