# Generated by Django 3.0.3 on 2020-04-02 09:27

import api.models.map.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("api", "0002_auto_20200402_1119"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuretype",
            name="feature_ctype",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.ContentType",
                validators=[api.models.map.validators.validate_feature_ctype],
            ),
        ),
        migrations.AlterField(
            model_name="featuretype",
            name="shape_ctype",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.ContentType",
                validators=[api.models.map.validators.validate_shape_ctype],
            ),
        ),
    ]
