# Generated by Django 3.0.3 on 2020-04-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0003_auto_20200402_1127")]

    operations = [migrations.RemoveField(model_name="feature", name="extra_props")]
