# Generated by Django 3.0.3 on 2020-02-28 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_parcel_geom"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[("name", models.SlugField(primary_key=True, serialize=False)),],
        ),
        migrations.CreateModel(
            name="CustomType",
            fields=[
                ("name", models.SlugField(primary_key=True, serialize=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_map_types",
                        to="api.Project",
                    ),
                ),
            ],
        ),
    ]
