# Generated by Django 3.0.3 on 2020-04-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0003_borders")]

    operations = [
        migrations.AlterModelOptions(
            name="borders", options={"verbose_name_plural": "borders"}
        ),
        migrations.AddField(
            model_name="borders",
            name="is_from_parcels",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="borders",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borders",
                to="api.Project",
            ),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcels",
                to="api.Project",
            ),
        ),
    ]
