# Generated by Django 3.0.3 on 2020-03-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0003_auto_20200326_1708")]

    operations = [
        migrations.CreateModel(
            name="DefaultDrawingClass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_model",
                    models.CharField(
                        choices=[
                            ("ArtificialArea", "ArtificialArea"),
                            ("Building", "Building"),
                            ("Parcel", "Parcel"),
                            ("Pathway", "Pathway"),
                            ("Wall", "Wall"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "drawing_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.DrawingClass",
                    ),
                ),
            ],
            options={"verbose_name_plural": "default drawing classes"},
        )
    ]
