# Generated by Django 3.0.3 on 2020-03-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0003_auto_20200328_1746")]

    operations = [
        migrations.AlterField(
            model_name="featurestyle",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="featurestyle", unique_together={("name", "feature_type")}
        ),
    ]
