# Generated by Django 3.0.3 on 2020-04-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0004_auto_20200404_1836")]

    operations = [
        migrations.AddField(
            model_name="featuretype",
            name="description",
            field=models.TextField(blank=True, default=""),
        )
    ]
