# Generated by Django 3.0.3 on 2020-03-29 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0004_auto_20200328_1849")]

    operations = [
        migrations.AlterField(
            model_name="circle",
            name="radius",
            field=models.FloatField(
                default=1, validators=[django.core.validators.MinValueValidator(0)]
            ),
        )
    ]
