# Generated by Django 3.0.3 on 2020-03-27 09:55

import api.models.map.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("api", "0004_defaultdrawingclass")]

    operations = [
        migrations.RemoveField(model_name="feature", name="category"),
        migrations.AddField(
            model_name="feature",
            name="extra_props",
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="FeatureType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "extra_props_schema",
                    jsonfield.fields.JSONField(
                        blank=True,
                        default=dict,
                        validators=[api.models.map.validators.validate_json_schema],
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.Category",
                    ),
                ),
            ],
            options={"verbose_name_plural": "feature types"},
        ),
        migrations.AddField(
            model_name="feature",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.FeatureType",
            ),
        ),
    ]
