# Generated by Django 3.0.3 on 2020-03-07 12:29

import api.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0004_auto_20200306_1740")]

    operations = [
        migrations.AlterField(
            model_name="circle",
            name="radius",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="map_lat",
            field=api.models.fields.LatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="map_lng",
            field=api.models.fields.LngField(
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ]
            ),
        ),
    ]
