# Generated by Django 3.0.3 on 2020-02-29 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_category_customtype_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="map_zoom",
            field=models.PositiveSmallIntegerField(
                default=19, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
