# Generated by Django 3.0.3 on 2020-04-02 14:07

import api.models.map.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("api", "0004_remove_feature_extra_props"),
    ]

    operations = [
        migrations.RemoveField(model_name="parcel", name="feature_ptr"),
        migrations.RemoveField(model_name="feature", name="style"),
        migrations.AddField(
            model_name="featurestyle",
            name="shape_ctype",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.ContentType",
                validators=[api.models.map.validators.validate_shape_ctype],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="featuretype",
            name="style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.FeatureStyle",
            ),
        ),
        migrations.AlterField(
            model_name="featurestyle",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(name="featurestyle", unique_together=set()),
        migrations.DeleteModel(name="Building"),
        migrations.DeleteModel(name="Parcel"),
        migrations.RemoveField(model_name="featurestyle", name="feature_type"),
    ]
