# Generated by Django 3.0.3 on 2020-04-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0005_featuretype_description")]

    operations = [
        migrations.AddField(
            model_name="viewfeature",
            name="max_zoom",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="viewfeature",
            name="min_zoom",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
