# Generated by Django 3.0.3 on 2020-03-27 13:42

import api.models.map.validators
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("api", "0005_auto_20200327_1055")]

    operations = [
        migrations.RenameField(
            model_name="feature", old_name="description", new_name="comments"
        ),
        migrations.AlterField(
            model_name="featuretype",
            name="extra_props_schema",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=None,
                null=True,
                validators=[api.models.map.validators.validate_json_schema],
            ),
        ),
    ]
