# Generated by Django 3.0.3 on 2020-03-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0005_auto_20200229_1109")]

    operations = [
        migrations.AlterUniqueTogether(
            name="parcel", unique_together={("project", "insee", "section", "number")}
        )
    ]
