# Generated by Django 3.0.3 on 2020-04-03 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0005_auto_20200402_1607")]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "feature_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.Feature",
                    ),
                ),
                (
                    "roof_surface",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="m²", null=True
                    ),
                ),
            ],
            options={"abstract": False, "base_manager_name": "objects"},
            bases=("api.feature",),
        )
    ]
