# Generated by Django 3.0.3 on 2020-02-28 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtype",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.Category",
            ),
        ),
        migrations.AddField(
            model_name="type",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.Category",
            ),
        ),
    ]
