# Generated by Django 3.0.3 on 2020-02-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20200228_1053"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtype",
            name="slug",
            field=models.SlugField(default="", primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="type",
            name="slug",
            field=models.SlugField(default="", primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customtype", name="name", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="type", name="name", field=models.CharField(max_length=50),
        ),
    ]
