# Generated by Django 3.0.3 on 2020-03-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0006_auto_20200307_1252")]

    operations = [
        migrations.AlterField(
            model_name="feature", name="name", field=models.CharField(max_length=50)
        )
    ]
