# Generated by Django 3.0.3 on 2020-03-03 18:04

import api.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0007_feature")]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="map_lat",
            field=api.models.fields.LatField(
                validators=[
                    django.core.validators.MinValueValidator(80),
                    django.core.validators.MaxValueValidator(90),
                    django.core.validators.MinValueValidator(80),
                    django.core.validators.MaxValueValidator(90),
                    django.core.validators.MinValueValidator(80),
                    django.core.validators.MaxValueValidator(90),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="map_lng",
            field=api.models.fields.LngField(
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ]
            ),
        ),
    ]
