# Generated by Django 3.0.3 on 2020-03-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0007_auto_20200308_1116")]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="categories",
            field=models.ManyToManyField(to="api.Category"),
        )
    ]
