# Generated by Django 3.0.3 on 2020-03-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0009_feature_permanence")]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="is_observation",
            field=models.BooleanField(default=True),
        )
    ]
