# Generated by Django 3.0.3 on 2020-03-05 13:27

import api.models.fields
import api.models.map.polygon
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_auto_20200305_1308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circle",
            name="lat",
            field=api.models.fields.LatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="circle",
            name="lng",
            field=api.models.fields.LngField(
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="lat",
            field=api.models.fields.LatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="lng",
            field=api.models.fields.LngField(
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="map_lat",
            field=api.models.fields.LatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="map_lng",
            field=api.models.fields.LngField(
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ]
            ),
        ),
        migrations.CreateModel(
            name="MultiPolygon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=50)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "coordinates",
                    jsonfield.fields.JSONField(
                        validators=[
                            api.models.map.polygon.validate_multipolygon_coordinates
                        ]
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.Project"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
