# Generated by Django 3.0.3 on 2020-03-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0011_feature_is_important")]

    operations = [
        migrations.CreateModel(
            name="View",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ViewFeature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("z_index", models.PositiveSmallIntegerField(default=0)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.Feature"
                    ),
                ),
                (
                    "view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.View"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="view",
            name="features",
            field=models.ManyToManyField(through="api.ViewFeature", to="api.Feature"),
        ),
        migrations.AddField(
            model_name="view",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.Project"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="view", unique_together={("project", "name")}
        ),
    ]
