# Generated by Django 3.0.3 on 2020-03-19 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("api", "0012_auto_20200310_1756")]

    operations = [
        migrations.RenameField(
            model_name="feature", old_name="is_important", new_name="is_risk"
        ),
        migrations.RenameField(
            model_name="feature", old_name="projection", new_name="map_projection"
        ),
        migrations.RemoveField(model_name="feature", name="is_observation"),
        migrations.AddField(
            model_name="feature",
            name="created_on",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feature",
            name="updated_on",
            field=models.DateField(auto_now=True),
        ),
    ]
