# Generated by Django 3.0.3 on 2020-03-19 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0013_auto_20200319_1712")]

    operations = [
        migrations.RenameField(
            model_name="feature", old_name="is_risk", new_name="is_risky"
        ),
        migrations.RemoveField(model_name="feature", name="categories"),
        migrations.AddField(
            model_name="feature",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.Category",
            ),
        ),
    ]
