# Generated by Django 3.0.3 on 2020-03-19 16:58

import api.models.map.feature
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0015_viewtilelayer")]

    operations = [
        migrations.CreateModel(
            name="FeatureAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload",
                    models.FileField(upload_to=api.models.map.feature.attachment_path),
                ),
                ("comments", models.TextField(blank=True, default="")),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="api.Feature",
                    ),
                ),
            ],
        )
    ]
