# Generated by Django 3.0.3 on 2020-03-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0016_featureattachment")]

    operations = [
        migrations.RenameField(
            model_name="feature", old_name="style", new_name="layer_options"
        )
    ]
