# Generated by Django 3.0.3 on 2020-03-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0017_auto_20200320_1408")]

    operations = [
        migrations.RenameField(
            model_name="feature", old_name="layer_options", new_name="path_options"
        )
    ]
