# Generated by Django 3.0.3 on 2020-03-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0018_auto_20200320_1413")]

    operations = [migrations.RemoveField(model_name="circle", name="radius")]
