# Generated by Django 3.0.3 on 2020-03-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0019_remove_circle_radius")]

    operations = [migrations.DeleteModel(name="ViewTileLayer")]
