# Generated by Django 3.0.3 on 2020-03-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0020_delete_viewtilelayer")]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "feature_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.Feature",
                    ),
                ),
                ("roof_surface", models.PositiveSmallIntegerField()),
            ],
            options={"abstract": False},
            bases=("api.feature",),
        )
    ]
