# Generated by Django 3.0.3 on 2020-03-21 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0021_building")]

    operations = [
        migrations.CreateModel(
            name="Wall",
            fields=[
                (
                    "feature_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.Feature",
                    ),
                ),
                (
                    "height",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="cm", null=True
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("api.feature",),
        ),
        migrations.AlterField(
            model_name="building",
            name="roof_surface",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="m²", null=True
            ),
        ),
    ]
