# Generated by Django 3.0.3 on 2020-03-21 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0022_auto_20200321_1526")]

    operations = [
        migrations.CreateModel(
            name="ArtificialArea",
            fields=[
                (
                    "feature_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.Feature",
                    ),
                ),
                (
                    "surface",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="m²", null=True
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("api.feature",),
        )
    ]
