# Generated by Django 3.0.3 on 2020-03-21 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0023_artificialarea")]

    operations = [
        migrations.CreateModel(
            name="Pathway",
            fields=[
                (
                    "feature_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.Feature",
                    ),
                ),
                ("is_road", models.BooleanField(null=True)),
            ],
            options={"abstract": False},
            bases=("api.feature",),
        )
    ]
