# Generated by Django 3.0.3 on 2020-03-22 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0024_pathway")]

    operations = [
        migrations.CreateModel(
            name="DefaultCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("Feature", "Feature"),
                            ("Polygon", "Polygon"),
                            ("MultiPolygon", "MultiPolygon"),
                            ("Parcel", "Parcel"),
                            ("Point", "Point"),
                            ("Circle", "Circle"),
                            ("Line", "Line"),
                            ("ArtificialArea", "ArtificialArea"),
                            ("Building", "Building"),
                            ("Pathway", "Pathway"),
                            ("Wall", "Wall"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.Category"
                    ),
                ),
            ],
        )
    ]
