# Generated by Django 3.0.3 on 2020-03-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0025_defaultcategory")]

    operations = [
        migrations.AlterField(
            model_name="defaultcategory",
            name="feature",
            field=models.CharField(
                choices=[
                    ("Parcel", "Parcel"),
                    ("ArtificialArea", "ArtificialArea"),
                    ("Building", "Building"),
                    ("Pathway", "Pathway"),
                    ("Wall", "Wall"),
                ],
                max_length=50,
                unique=True,
            ),
        )
    ]
