# Generated by Django 3.1.3 on 2020-11-28 18:34

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import map_types.models.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureStyle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeatureType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("needs", models.TextField(blank=True, default="")),
                ("contributions", models.TextField(blank=True, default="")),
            ],
            options={"verbose_name_plural": "feature types",},
        ),
        migrations.CreateModel(
            name="Shape",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "map_projection",
                    models.CharField(default="EPSG:3857", max_length=50),
                ),
                ("zoom", models.PositiveSmallIntegerField(default=19)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_map_types.shape_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={"unique_together": {("content_type", "object_id")},},
        ),
        migrations.CreateModel(
            name="ShapeStyle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_map_types.shapestyle_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={"abstract": False, "base_manager_name": "objects",},
        ),
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "shape_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="map_types.shape",
                    ),
                ),
                (
                    "coordinates",
                    jsonfield.fields.JSONField(blank=True, default=None, null=True),
                ),
                (
                    "radius",
                    models.FloatField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("map_types.shape",),
        ),
        migrations.CreateModel(
            name="CircleStyle",
            fields=[
                (
                    "shapestyle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="map_types.shapestyle",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(default="#FFFFFF", max_length=18),
                ),
                ("weight", models.PositiveSmallIntegerField()),
                (
                    "opacity",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "dash_array",
                    models.CharField(
                        max_length=50,
                        validators=[map_types.models.validators.validate_dash_array],
                    ),
                ),
                ("icon", models.ImageField(upload_to="")),
            ],
            options={"abstract": False,},
            bases=("map_types.shapestyle", models.Model),
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "shape_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="map_types.shape",
                    ),
                ),
                (
                    "coordinates",
                    jsonfield.fields.JSONField(blank=True, default=None, null=True),
                ),
            ],
            options={"abstract": False,},
            bases=("map_types.shape",),
        ),
        migrations.CreateModel(
            name="LineStyle",
            fields=[
                (
                    "shapestyle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="map_types.shapestyle",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(default="#FFFFFF", max_length=18),
                ),
                ("weight", models.PositiveSmallIntegerField()),
                (
                    "opacity",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "dash_array",
                    models.CharField(
                        max_length=50,
                        validators=[map_types.models.validators.validate_dash_array],
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("map_types.shapestyle", models.Model),
        ),
        migrations.CreateModel(
            name="MultiPolygon",
            fields=[
                (
                    "shape_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="map_types.shape",
                    ),
                ),
                (
                    "coordinates",
                    jsonfield.fields.JSONField(blank=True, default=None, null=True),
                ),
            ],
            options={"abstract": False,},
            bases=("map_types.shape",),
        ),
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "shape_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="map_types.shape",
                    ),
                ),
                (
                    "coordinates",
                    jsonfield.fields.JSONField(blank=True, default=None, null=True),
                ),
            ],
            options={"abstract": False,},
            bases=("map_types.shape",),
        ),
        migrations.CreateModel(
            name="PointStyle",
            fields=[
                (
                    "shapestyle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="map_types.shapestyle",
                    ),
                ),
                ("icon", models.ImageField(upload_to="")),
            ],
            options={"abstract": False,},
            bases=("map_types.shapestyle", models.Model),
        ),
        migrations.CreateModel(
            name="Polygon",
            fields=[
                (
                    "shape_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="map_types.shape",
                    ),
                ),
                (
                    "coordinates",
                    jsonfield.fields.JSONField(blank=True, default=None, null=True),
                ),
            ],
            options={"abstract": False,},
            bases=("map_types.shape",),
        ),
        migrations.CreateModel(
            name="PolygonStyle",
            fields=[
                (
                    "shapestyle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="map_types.shapestyle",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(default="#FFFFFF", max_length=18),
                ),
                ("weight", models.PositiveSmallIntegerField()),
                (
                    "opacity",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "dash_array",
                    models.CharField(
                        max_length=50,
                        validators=[map_types.models.validators.validate_dash_array],
                    ),
                ),
                (
                    "fill_color",
                    colorfield.fields.ColorField(default="#FFFFFF", max_length=18),
                ),
                (
                    "fill_opacity",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("map_types.shapestyle", models.Model),
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "feature_types",
                    models.ManyToManyField(
                        through="map_types.FeatureStyle", to="map_types.FeatureType"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="featurestyle",
            name="feature_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="map_types.featuretype"
            ),
        ),
        migrations.AddField(
            model_name="featurestyle",
            name="shape_ctype",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
                validators=[map_types.models.validators.validate_shape_ctype],
            ),
        ),
        migrations.AddField(
            model_name="featurestyle",
            name="style",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="map_types.shapestyle"
            ),
        ),
        migrations.AddField(
            model_name="featurestyle",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="map_types.theme"
            ),
        ),
    ]
