# Generated by Django 3.1.3 on 2020-12-20 09:20

import colorfield.fields
import designs.models.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("designs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circlestyle",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", help_text="A valid CSS color.", max_length=18
            ),
        ),
        migrations.AlterField(
            model_name="circlestyle",
            name="opacity",
            field=models.PositiveSmallIntegerField(
                default=100,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="opacity (%)",
            ),
        ),
        migrations.AlterField(
            model_name="linestyle",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", help_text="A valid CSS color.", max_length=18
            ),
        ),
        migrations.AlterField(
            model_name="linestyle",
            name="opacity",
            field=models.PositiveSmallIntegerField(
                default=100,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="opacity (%)",
            ),
        ),
        migrations.AlterField(
            model_name="mapelementtype",
            name="shape_ctype",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="contenttypes.contenttype",
                validators=[designs.models.validators.validate_shape_ctype],
                verbose_name="shape type",
            ),
        ),
        migrations.AlterField(
            model_name="polygonstyle",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", help_text="A valid CSS color.", max_length=18
            ),
        ),
        migrations.AlterField(
            model_name="polygonstyle",
            name="fill_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", help_text="A valid CSS color.", max_length=18
            ),
        ),
        migrations.AlterField(
            model_name="polygonstyle",
            name="fill_opacity",
            field=models.PositiveSmallIntegerField(
                default=100,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="fill opacity (%)",
            ),
        ),
        migrations.AlterField(
            model_name="polygonstyle",
            name="opacity",
            field=models.PositiveSmallIntegerField(
                default=100,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="opacity (%)",
            ),
        ),
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                ("map_center", djgeojson.fields.PointField()),
                ("map_zoom", models.PositiveSmallIntegerField(default=19)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
