# Generated by Django 3.1.3 on 2020-12-20 13:21

import designs.models.design
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("designs", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="design",
            name="map_theme",
            field=models.ForeignKey(
                default=designs.models.design.get_default_map_theme,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="designs.maptheme",
            ),
        )
    ]
