# Generated by Django 3.1.3 on 2020-12-20 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("designs", "0002_auto_20201220_1020"),
    ]

    operations = [
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("needs", models.TextField(blank=True, default="")),
                ("contributions", models.TextField(blank=True, default="")),
                (
                    "element_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="designs.elementtype",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_designs.element_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={"ordering": ["name"]},
            managers=[
                ("tagged", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MapElement",
            fields=[
                (
                    "element_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="designs.element",
                    ),
                )
            ],
            options={"abstract": False, "base_manager_name": "objects"},
            bases=("designs.element",),
            managers=[
                ("tagged", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="shape",
            name="map_element",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shape",
                to="designs.mapelement",
            ),
            preserve_default=False,
        ),
    ]
