# Generated by Django 3.1.3 on 2021-01-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("designs", "0002_auto_20201220_1421"),
    ]

    operations = [
        migrations.AlterModelManagers(name="element", managers=[],),
        migrations.AlterModelManagers(name="mapelement", managers=[],),
        migrations.AddField(
            model_name="element",
            name="observation_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
