# Generated by Django 3.1.3 on 2020-12-20 11:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("designs", "0003_auto_20201220_1046")]

    operations = [
        migrations.AddField(
            model_name="element",
            name="design",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="designs.design",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="circlestyle",
            name="opacity",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="Zero means no stroke.",
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="opacity (%)",
            ),
        ),
        migrations.AlterField(
            model_name="linestyle",
            name="opacity",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="Zero means no stroke.",
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="opacity (%)",
            ),
        ),
        migrations.AlterField(
            model_name="polygonstyle",
            name="fill_opacity",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="Zero means no fill.",
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="fill opacity (%)",
            ),
        ),
        migrations.AlterField(
            model_name="polygonstyle",
            name="opacity",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="Zero means no stroke.",
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="opacity (%)",
            ),
        ),
    ]
