# Generated by Django 3.1.3 on 2020-12-20 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("designs", "0004_auto_20201220_1229")]

    operations = [
        migrations.AlterField(
            model_name="design",
            name="map_zoom",
            field=models.PositiveSmallIntegerField(default=17),
        ),
        migrations.AlterField(
            model_name="shape",
            name="edit_zoom",
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_theme",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="designs.theme",
                    ),
                ),
            ],
            options={"verbose_name": "site configuration"},
        ),
    ]
