# Generated by Django 3.1.3 on 2020-12-20 13:09

import designs.models.design
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("designs", "0005_auto_20201220_1401")]

    operations = [
        migrations.AddField(
            model_name="design",
            name="theme",
            field=models.ForeignKey(
                default=designs.models.design.get_default_theme,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="designs.theme",
            ),
        )
    ]
