# Generated by Django 3.1.3 on 2021-01-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("designs", "0005_element_permanence"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="is_risky",
            field=models.BooleanField(default=False),
        ),
    ]
