# Generated by Django 3.1.3 on 2021-01-12 18:00

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ("designs", "0006_element_is_risky"),
    ]

    operations = [
        migrations.CreateModel(
            name="Geometry",
            fields=[
                (
                    "shape_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="designs.shape",
                    ),
                ),
                ("geom", djgeojson.fields.GeometryCollectionField()),
            ],
            options={
                "abstract": False,
            },
            bases=("designs.shape",),
        ),
    ]
