# Generated by Django 3.1.3 on 2021-01-15 17:02

import designs.models.element
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("designs", "0007_geometry"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElementAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload",
                    models.FileField(upload_to=designs.models.element.attachment_path),
                ),
                ("comments", models.TextField(blank=True, default="")),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="designs.element",
                    ),
                ),
            ],
        ),
    ]
