# Generated by Django 3.2.10 on 2021-12-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("designs", "0008_elementattachment"),
    ]

    operations = [
        migrations.RemoveField(model_name="design", name="slug",),
        migrations.AlterField(
            model_name="design", name="name", field=models.CharField(max_length=100),
        ),
    ]
