# Generated by Django 3.2.10 on 2021-12-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("designs", "0009_auto_20211230_2104"),
    ]

    operations = [
        migrations.RemoveField(model_name="elementtype", name="contributions",),
        migrations.RemoveField(model_name="elementtype", name="needs",),
    ]
