# Generated by Django 3.2.10 on 2022-01-06 14:44

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("designs", "0013_auto_20211230_2156"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="elementtype",
            options={
                "default_manager_name": "objects",
                "ordering": ["name"],
                "verbose_name_plural": "element types",
            },
        ),
        migrations.AlterModelManagers(name="elementtype", managers=[],),
        migrations.AlterModelManagers(name="mapelementtype", managers=[],),
        migrations.CreateModel(
            name="ElementTypeCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("slug", models.SlugField(verbose_name="slug")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="designs.elementtypecategory",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={"verbose_name": "category", "verbose_name_plural": "categories",},
            managers=[("tree", django.db.models.manager.Manager()),],
        ),
        migrations.AddField(
            model_name="elementtype",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="element_types",
                to="designs.ElementTypeCategory",
            ),
        ),
    ]
