# Generated by Django 3.2.10 on 2022-01-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("designs", "0014_auto_20220106_1544"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuration", options={"verbose_name": "global configuration"},
        ),
    ]
